
@scrollHide = ->
  # Hide Header on on scroll down
  didScroll = undefined
  lastScrollTop = 0
  delta = 5
  navbarHeight = $('.current-page .p-header').outerHeight()

  hasScrolled = ->
    st = $('.current-page .p-body-inner').scrollTop()
    # Make sure they scroll more than delta
    if Math.abs(lastScrollTop - st) <= delta
      return
    # If they scrolled down and are past the navbar, add class .p-header-up.
    # This is necessary so you never see what is "behind" the navbar.
    if st > lastScrollTop and st > navbarHeight
      # Scroll Down
      $('.current-page .p-header').removeClass('p-header-down').addClass 'p-header-up'
    else
      # Scroll Up
      if st + $('.p-body-inner').height() < $('.page.current-page').height()
        $('.current-page .p-header').removeClass('p-header-up').addClass 'p-header-down'
    lastScrollTop = st
    return

  $('.p-body-inner').scroll (event) ->
    didScroll = true
    return
  setInterval (->
    if didScroll
      hasScrolled()
      didScroll = false
    return
  ), 250

  # ---
  # generated by js2coffee 2.1.0